// Code generated by internal/asdlgen. DO NOT EDIT.
// Source: internal/asdlgen/Python.asdl

package ast

// FieldInfo describes one field on an AST node, in the order CPython's
// _fields tuple lists them. Kind tells the renderer how to walk the value:
// scalar fields print their Go value; node fields recurse; seq fields render
// as Python lists.
type FieldInfo struct {
	Name     string // ASDL/Python field name (e.g. "decorator_list")
	GoName   string // Go field name           (e.g. "DecoratorList")
	Kind     FieldKind
	Optional bool // ASDL ? marker; sequence fields are implicitly optional.
}

type FieldKind uint8

const (
	FieldScalar FieldKind = iota // string, int, Constant
	FieldNode                    // single AST node (interface or *Struct)
	FieldSeq                     // []Node
	FieldOptSeq                  // []Node where elements may be nil (Dict.keys)
)

// NodeInfo holds the dump metadata for one constructor or product type.
type NodeInfo struct {
	PyName     string      // e.g. "BinOp"
	Fields     []FieldInfo // _fields tuple order
	Attributes []FieldInfo // _attributes tuple, if any
}

// nodeInfoTable is keyed by Go type name (without the package prefix).
var nodeInfoTable = map[string]*NodeInfo{
	"Alias": {
		PyName: "alias",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: false},
			{Name: "asname", GoName: "Asname", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Arg": {
		PyName: "arg",
		Fields: []FieldInfo{
			{Name: "arg", GoName: "Arg", Kind: FieldScalar, Optional: false},
			{Name: "annotation", GoName: "Annotation", Kind: FieldNode, Optional: true},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Arguments": {
		PyName: "arguments",
		Fields: []FieldInfo{
			{Name: "posonlyargs", GoName: "Posonlyargs", Kind: FieldSeq, Optional: true},
			{Name: "args", GoName: "Args", Kind: FieldSeq, Optional: true},
			{Name: "vararg", GoName: "Vararg", Kind: FieldNode, Optional: true},
			{Name: "kwonlyargs", GoName: "Kwonlyargs", Kind: FieldSeq, Optional: true},
			{Name: "kw_defaults", GoName: "KwDefaults", Kind: FieldOptSeq, Optional: true},
			{Name: "kwarg", GoName: "Kwarg", Kind: FieldNode, Optional: true},
			{Name: "defaults", GoName: "Defaults", Kind: FieldSeq, Optional: true},
		},
	},
	"And": {
		PyName: "And",
	},
	"Or": {
		PyName: "Or",
	},
	"Eq": {
		PyName: "Eq",
	},
	"NotEq": {
		PyName: "NotEq",
	},
	"Lt": {
		PyName: "Lt",
	},
	"LtE": {
		PyName: "LtE",
	},
	"Gt": {
		PyName: "Gt",
	},
	"GtE": {
		PyName: "GtE",
	},
	"Is": {
		PyName: "Is",
	},
	"IsNot": {
		PyName: "IsNot",
	},
	"In": {
		PyName: "In",
	},
	"NotIn": {
		PyName: "NotIn",
	},
	"Comprehension": {
		PyName: "comprehension",
		Fields: []FieldInfo{
			{Name: "target", GoName: "Target", Kind: FieldNode, Optional: false},
			{Name: "iter", GoName: "Iter", Kind: FieldNode, Optional: false},
			{Name: "ifs", GoName: "Ifs", Kind: FieldSeq, Optional: true},
			{Name: "is_async", GoName: "IsAsync", Kind: FieldScalar, Optional: false},
		},
	},
	"ExceptHandler": {
		PyName: "ExceptHandler",
		Fields: []FieldInfo{
			{Name: "type", GoName: "Type", Kind: FieldNode, Optional: true},
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: true},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"BoolOp": {
		PyName: "BoolOp",
		Fields: []FieldInfo{
			{Name: "op", GoName: "Op", Kind: FieldNode, Optional: false},
			{Name: "values", GoName: "Values", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"NamedExpr": {
		PyName: "NamedExpr",
		Fields: []FieldInfo{
			{Name: "target", GoName: "Target", Kind: FieldNode, Optional: false},
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"BinOp": {
		PyName: "BinOp",
		Fields: []FieldInfo{
			{Name: "left", GoName: "Left", Kind: FieldNode, Optional: false},
			{Name: "op", GoName: "Op", Kind: FieldNode, Optional: false},
			{Name: "right", GoName: "Right", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"UnaryOp": {
		PyName: "UnaryOp",
		Fields: []FieldInfo{
			{Name: "op", GoName: "Op", Kind: FieldNode, Optional: false},
			{Name: "operand", GoName: "Operand", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Lambda": {
		PyName: "Lambda",
		Fields: []FieldInfo{
			{Name: "args", GoName: "Args", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"IfExp": {
		PyName: "IfExp",
		Fields: []FieldInfo{
			{Name: "test", GoName: "Test", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldNode, Optional: false},
			{Name: "orelse", GoName: "Orelse", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Dict": {
		PyName: "Dict",
		Fields: []FieldInfo{
			{Name: "keys", GoName: "Keys", Kind: FieldOptSeq, Optional: true},
			{Name: "values", GoName: "Values", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Set": {
		PyName: "Set",
		Fields: []FieldInfo{
			{Name: "elts", GoName: "Elts", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"ListComp": {
		PyName: "ListComp",
		Fields: []FieldInfo{
			{Name: "elt", GoName: "Elt", Kind: FieldNode, Optional: false},
			{Name: "generators", GoName: "Generators", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"SetComp": {
		PyName: "SetComp",
		Fields: []FieldInfo{
			{Name: "elt", GoName: "Elt", Kind: FieldNode, Optional: false},
			{Name: "generators", GoName: "Generators", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"DictComp": {
		PyName: "DictComp",
		Fields: []FieldInfo{
			{Name: "key", GoName: "Key", Kind: FieldNode, Optional: false},
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
			{Name: "generators", GoName: "Generators", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"GeneratorExp": {
		PyName: "GeneratorExp",
		Fields: []FieldInfo{
			{Name: "elt", GoName: "Elt", Kind: FieldNode, Optional: false},
			{Name: "generators", GoName: "Generators", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Await": {
		PyName: "Await",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Yield": {
		PyName: "Yield",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"YieldFrom": {
		PyName: "YieldFrom",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Compare": {
		PyName: "Compare",
		Fields: []FieldInfo{
			{Name: "left", GoName: "Left", Kind: FieldNode, Optional: false},
			{Name: "ops", GoName: "Ops", Kind: FieldSeq, Optional: true},
			{Name: "comparators", GoName: "Comparators", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Call": {
		PyName: "Call",
		Fields: []FieldInfo{
			{Name: "func", GoName: "Func", Kind: FieldNode, Optional: false},
			{Name: "args", GoName: "Args", Kind: FieldSeq, Optional: true},
			{Name: "keywords", GoName: "Keywords", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"FormattedValue": {
		PyName: "FormattedValue",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
			{Name: "conversion", GoName: "Conversion", Kind: FieldScalar, Optional: false},
			{Name: "format_spec", GoName: "FormatSpec", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Interpolation": {
		PyName: "Interpolation",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
			{Name: "str", GoName: "Str", Kind: FieldScalar, Optional: false},
			{Name: "conversion", GoName: "Conversion", Kind: FieldScalar, Optional: false},
			{Name: "format_spec", GoName: "FormatSpec", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"JoinedStr": {
		PyName: "JoinedStr",
		Fields: []FieldInfo{
			{Name: "values", GoName: "Values", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"TemplateStr": {
		PyName: "TemplateStr",
		Fields: []FieldInfo{
			{Name: "values", GoName: "Values", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Constant": {
		PyName: "Constant",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldScalar, Optional: false},
			{Name: "kind", GoName: "Kind", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Attribute": {
		PyName: "Attribute",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
			{Name: "attr", GoName: "Attr", Kind: FieldScalar, Optional: false},
			{Name: "ctx", GoName: "Ctx", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Subscript": {
		PyName: "Subscript",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
			{Name: "slice", GoName: "Slice", Kind: FieldNode, Optional: false},
			{Name: "ctx", GoName: "Ctx", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Starred": {
		PyName: "Starred",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
			{Name: "ctx", GoName: "Ctx", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Name": {
		PyName: "Name",
		Fields: []FieldInfo{
			{Name: "id", GoName: "Id", Kind: FieldScalar, Optional: false},
			{Name: "ctx", GoName: "Ctx", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"List": {
		PyName: "List",
		Fields: []FieldInfo{
			{Name: "elts", GoName: "Elts", Kind: FieldSeq, Optional: true},
			{Name: "ctx", GoName: "Ctx", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Tuple": {
		PyName: "Tuple",
		Fields: []FieldInfo{
			{Name: "elts", GoName: "Elts", Kind: FieldSeq, Optional: true},
			{Name: "ctx", GoName: "Ctx", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Slice": {
		PyName: "Slice",
		Fields: []FieldInfo{
			{Name: "lower", GoName: "Lower", Kind: FieldNode, Optional: true},
			{Name: "upper", GoName: "Upper", Kind: FieldNode, Optional: true},
			{Name: "step", GoName: "Step", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Load": {
		PyName: "Load",
	},
	"Store": {
		PyName: "Store",
	},
	"Del": {
		PyName: "Del",
	},
	"Keyword": {
		PyName: "keyword",
		Fields: []FieldInfo{
			{Name: "arg", GoName: "Arg", Kind: FieldScalar, Optional: true},
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchCase": {
		PyName: "match_case",
		Fields: []FieldInfo{
			{Name: "pattern", GoName: "Pattern", Kind: FieldNode, Optional: false},
			{Name: "guard", GoName: "Guard", Kind: FieldNode, Optional: true},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
		},
	},
	"Module": {
		PyName: "Module",
		Fields: []FieldInfo{
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "type_ignores", GoName: "TypeIgnores", Kind: FieldSeq, Optional: true},
		},
	},
	"Interactive": {
		PyName: "Interactive",
		Fields: []FieldInfo{
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
		},
	},
	"Expression": {
		PyName: "Expression",
		Fields: []FieldInfo{
			{Name: "body", GoName: "Body", Kind: FieldNode, Optional: false},
		},
	},
	"FunctionType": {
		PyName: "FunctionType",
		Fields: []FieldInfo{
			{Name: "argtypes", GoName: "Argtypes", Kind: FieldSeq, Optional: true},
			{Name: "returns", GoName: "Returns", Kind: FieldNode, Optional: false},
		},
	},
	"Add": {
		PyName: "Add",
	},
	"Sub": {
		PyName: "Sub",
	},
	"Mult": {
		PyName: "Mult",
	},
	"MatMult": {
		PyName: "MatMult",
	},
	"Div": {
		PyName: "Div",
	},
	"Mod": {
		PyName: "Mod",
	},
	"Pow": {
		PyName: "Pow",
	},
	"LShift": {
		PyName: "LShift",
	},
	"RShift": {
		PyName: "RShift",
	},
	"BitOr": {
		PyName: "BitOr",
	},
	"BitXor": {
		PyName: "BitXor",
	},
	"BitAnd": {
		PyName: "BitAnd",
	},
	"FloorDiv": {
		PyName: "FloorDiv",
	},
	"MatchValue": {
		PyName: "MatchValue",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchSingleton": {
		PyName: "MatchSingleton",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldScalar, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchSequence": {
		PyName: "MatchSequence",
		Fields: []FieldInfo{
			{Name: "patterns", GoName: "Patterns", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchMapping": {
		PyName: "MatchMapping",
		Fields: []FieldInfo{
			{Name: "keys", GoName: "Keys", Kind: FieldSeq, Optional: true},
			{Name: "patterns", GoName: "Patterns", Kind: FieldSeq, Optional: true},
			{Name: "rest", GoName: "Rest", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchClass": {
		PyName: "MatchClass",
		Fields: []FieldInfo{
			{Name: "cls", GoName: "Cls", Kind: FieldNode, Optional: false},
			{Name: "patterns", GoName: "Patterns", Kind: FieldSeq, Optional: true},
			{Name: "kwd_attrs", GoName: "KwdAttrs", Kind: FieldSeq, Optional: true},
			{Name: "kwd_patterns", GoName: "KwdPatterns", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchStar": {
		PyName: "MatchStar",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchAs": {
		PyName: "MatchAs",
		Fields: []FieldInfo{
			{Name: "pattern", GoName: "Pattern", Kind: FieldNode, Optional: true},
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"MatchOr": {
		PyName: "MatchOr",
		Fields: []FieldInfo{
			{Name: "patterns", GoName: "Patterns", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"FunctionDef": {
		PyName: "FunctionDef",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: false},
			{Name: "args", GoName: "Args", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "decorator_list", GoName: "DecoratorList", Kind: FieldSeq, Optional: true},
			{Name: "returns", GoName: "Returns", Kind: FieldNode, Optional: true},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
			{Name: "type_params", GoName: "TypeParams", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"AsyncFunctionDef": {
		PyName: "AsyncFunctionDef",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: false},
			{Name: "args", GoName: "Args", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "decorator_list", GoName: "DecoratorList", Kind: FieldSeq, Optional: true},
			{Name: "returns", GoName: "Returns", Kind: FieldNode, Optional: true},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
			{Name: "type_params", GoName: "TypeParams", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"ClassDef": {
		PyName: "ClassDef",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: false},
			{Name: "bases", GoName: "Bases", Kind: FieldSeq, Optional: true},
			{Name: "keywords", GoName: "Keywords", Kind: FieldSeq, Optional: true},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "decorator_list", GoName: "DecoratorList", Kind: FieldSeq, Optional: true},
			{Name: "type_params", GoName: "TypeParams", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Return": {
		PyName: "Return",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Delete": {
		PyName: "Delete",
		Fields: []FieldInfo{
			{Name: "targets", GoName: "Targets", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Assign": {
		PyName: "Assign",
		Fields: []FieldInfo{
			{Name: "targets", GoName: "Targets", Kind: FieldSeq, Optional: true},
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"TypeAlias": {
		PyName: "TypeAlias",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldNode, Optional: false},
			{Name: "type_params", GoName: "TypeParams", Kind: FieldSeq, Optional: true},
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"AugAssign": {
		PyName: "AugAssign",
		Fields: []FieldInfo{
			{Name: "target", GoName: "Target", Kind: FieldNode, Optional: false},
			{Name: "op", GoName: "Op", Kind: FieldNode, Optional: false},
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"AnnAssign": {
		PyName: "AnnAssign",
		Fields: []FieldInfo{
			{Name: "target", GoName: "Target", Kind: FieldNode, Optional: false},
			{Name: "annotation", GoName: "Annotation", Kind: FieldNode, Optional: false},
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: true},
			{Name: "simple", GoName: "Simple", Kind: FieldScalar, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"For": {
		PyName: "For",
		Fields: []FieldInfo{
			{Name: "target", GoName: "Target", Kind: FieldNode, Optional: false},
			{Name: "iter", GoName: "Iter", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "orelse", GoName: "Orelse", Kind: FieldSeq, Optional: true},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"AsyncFor": {
		PyName: "AsyncFor",
		Fields: []FieldInfo{
			{Name: "target", GoName: "Target", Kind: FieldNode, Optional: false},
			{Name: "iter", GoName: "Iter", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "orelse", GoName: "Orelse", Kind: FieldSeq, Optional: true},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"While": {
		PyName: "While",
		Fields: []FieldInfo{
			{Name: "test", GoName: "Test", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "orelse", GoName: "Orelse", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"If": {
		PyName: "If",
		Fields: []FieldInfo{
			{Name: "test", GoName: "Test", Kind: FieldNode, Optional: false},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "orelse", GoName: "Orelse", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"With": {
		PyName: "With",
		Fields: []FieldInfo{
			{Name: "items", GoName: "Items", Kind: FieldSeq, Optional: true},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"AsyncWith": {
		PyName: "AsyncWith",
		Fields: []FieldInfo{
			{Name: "items", GoName: "Items", Kind: FieldSeq, Optional: true},
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "type_comment", GoName: "TypeComment", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Match": {
		PyName: "Match",
		Fields: []FieldInfo{
			{Name: "subject", GoName: "Subject", Kind: FieldNode, Optional: false},
			{Name: "cases", GoName: "Cases", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Raise": {
		PyName: "Raise",
		Fields: []FieldInfo{
			{Name: "exc", GoName: "Exc", Kind: FieldNode, Optional: true},
			{Name: "cause", GoName: "Cause", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Try": {
		PyName: "Try",
		Fields: []FieldInfo{
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "handlers", GoName: "Handlers", Kind: FieldSeq, Optional: true},
			{Name: "orelse", GoName: "Orelse", Kind: FieldSeq, Optional: true},
			{Name: "finalbody", GoName: "Finalbody", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"TryStar": {
		PyName: "TryStar",
		Fields: []FieldInfo{
			{Name: "body", GoName: "Body", Kind: FieldSeq, Optional: true},
			{Name: "handlers", GoName: "Handlers", Kind: FieldSeq, Optional: true},
			{Name: "orelse", GoName: "Orelse", Kind: FieldSeq, Optional: true},
			{Name: "finalbody", GoName: "Finalbody", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Assert": {
		PyName: "Assert",
		Fields: []FieldInfo{
			{Name: "test", GoName: "Test", Kind: FieldNode, Optional: false},
			{Name: "msg", GoName: "Msg", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Import": {
		PyName: "Import",
		Fields: []FieldInfo{
			{Name: "names", GoName: "Names", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"ImportFrom": {
		PyName: "ImportFrom",
		Fields: []FieldInfo{
			{Name: "module", GoName: "Module", Kind: FieldScalar, Optional: true},
			{Name: "names", GoName: "Names", Kind: FieldSeq, Optional: true},
			{Name: "level", GoName: "Level", Kind: FieldScalar, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Global": {
		PyName: "Global",
		Fields: []FieldInfo{
			{Name: "names", GoName: "Names", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Nonlocal": {
		PyName: "Nonlocal",
		Fields: []FieldInfo{
			{Name: "names", GoName: "Names", Kind: FieldSeq, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Expr": {
		PyName: "Expr",
		Fields: []FieldInfo{
			{Name: "value", GoName: "Value", Kind: FieldNode, Optional: false},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Pass": {
		PyName: "Pass",
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Break": {
		PyName: "Break",
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Continue": {
		PyName: "Continue",
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"TypeIgnore": {
		PyName: "TypeIgnore",
		Fields: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar, Optional: false},
			{Name: "tag", GoName: "Tag", Kind: FieldScalar, Optional: false},
		},
	},
	"TypeVar": {
		PyName: "TypeVar",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: false},
			{Name: "bound", GoName: "Bound", Kind: FieldNode, Optional: true},
			{Name: "default_value", GoName: "DefaultValue", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"ParamSpec": {
		PyName: "ParamSpec",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: false},
			{Name: "default_value", GoName: "DefaultValue", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"TypeVarTuple": {
		PyName: "TypeVarTuple",
		Fields: []FieldInfo{
			{Name: "name", GoName: "Name", Kind: FieldScalar, Optional: false},
			{Name: "default_value", GoName: "DefaultValue", Kind: FieldNode, Optional: true},
		},
		Attributes: []FieldInfo{
			{Name: "lineno", GoName: "Lineno", Kind: FieldScalar},
			{Name: "col_offset", GoName: "ColOffset", Kind: FieldScalar},
			{Name: "end_lineno", GoName: "EndLineno", Kind: FieldScalar},
			{Name: "end_col_offset", GoName: "EndColOffset", Kind: FieldScalar},
		},
	},
	"Invert": {
		PyName: "Invert",
	},
	"Not": {
		PyName: "Not",
	},
	"UAdd": {
		PyName: "UAdd",
	},
	"USub": {
		PyName: "USub",
	},
	"Withitem": {
		PyName: "withitem",
		Fields: []FieldInfo{
			{Name: "context_expr", GoName: "ContextExpr", Kind: FieldNode, Optional: false},
			{Name: "optional_vars", GoName: "OptionalVars", Kind: FieldNode, Optional: true},
		},
	},
}

// LookupNodeInfo returns the dump metadata for a Go type name (e.g. "BinOp").
func LookupNodeInfo(goName string) *NodeInfo { return nodeInfoTable[goName] }
