// Code generated by internal/asdlgen. DO NOT EDIT.
// Source: internal/asdlgen/Python.asdl

package ast

// Pos carries source positions copied directly from the lexer. CPython uses
// 1-indexed lineno and 0-indexed UTF-8 byte col_offset; we match that
// exactly so ast.dump output is byte-equal.
type Pos struct {
	Lineno       int
	ColOffset    int
	EndLineno    int
	EndColOffset int
}

// pos returns p (used by generated GetPos methods).
func (p Pos) pos() Pos { return p }

// Alias is the ASDL product type `alias`.
type Alias struct {
	Pos
	Name   string // identifier name
	Asname string // identifier? asname
}

func (n *Alias) GetPos() Pos { return n.Pos }

// Arg is the ASDL product type `arg`.
type Arg struct {
	Pos
	Arg         string   // identifier arg
	Annotation  ExprNode // expr? annotation
	TypeComment string   // string? type_comment
}

func (n *Arg) GetPos() Pos { return n.Pos }

// Arguments is the ASDL product type `arguments`.
type Arguments struct {
	Posonlyargs []*Arg     // arg* posonlyargs
	Args        []*Arg     // arg* args
	Vararg      *Arg       // arg? vararg
	Kwonlyargs  []*Arg     // arg* kwonlyargs
	KwDefaults  []ExprNode // expr?* kw_defaults
	Kwarg       *Arg       // arg? kwarg
	Defaults    []ExprNode // expr* defaults
}

// BoolopNode is the ASDL sum type `boolop` (one of 2 constructors).
type BoolopNode interface {
	isBoolopNode()
}

// And is the `And` constructor of BoolopNode.
type And struct {
}

func (*And) isBoolopNode() {}

// Or is the `Or` constructor of BoolopNode.
type Or struct {
}

func (*Or) isBoolopNode() {}

// CmpopNode is the ASDL sum type `cmpop` (one of 10 constructors).
type CmpopNode interface {
	isCmpopNode()
}

// Eq is the `Eq` constructor of CmpopNode.
type Eq struct {
}

func (*Eq) isCmpopNode() {}

// NotEq is the `NotEq` constructor of CmpopNode.
type NotEq struct {
}

func (*NotEq) isCmpopNode() {}

// Lt is the `Lt` constructor of CmpopNode.
type Lt struct {
}

func (*Lt) isCmpopNode() {}

// LtE is the `LtE` constructor of CmpopNode.
type LtE struct {
}

func (*LtE) isCmpopNode() {}

// Gt is the `Gt` constructor of CmpopNode.
type Gt struct {
}

func (*Gt) isCmpopNode() {}

// GtE is the `GtE` constructor of CmpopNode.
type GtE struct {
}

func (*GtE) isCmpopNode() {}

// Is is the `Is` constructor of CmpopNode.
type Is struct {
}

func (*Is) isCmpopNode() {}

// IsNot is the `IsNot` constructor of CmpopNode.
type IsNot struct {
}

func (*IsNot) isCmpopNode() {}

// In is the `In` constructor of CmpopNode.
type In struct {
}

func (*In) isCmpopNode() {}

// NotIn is the `NotIn` constructor of CmpopNode.
type NotIn struct {
}

func (*NotIn) isCmpopNode() {}

// Comprehension is the ASDL product type `comprehension`.
type Comprehension struct {
	Target  ExprNode   // expr target
	Iter    ExprNode   // expr iter
	Ifs     []ExprNode // expr* ifs
	IsAsync int        // int is_async
}

// ExcepthandlerNode is the ASDL sum type `excepthandler` (one of 1 constructors).
type ExcepthandlerNode interface {
	isExcepthandlerNode()
	GetPos() Pos
}

// ExceptHandler is the `ExceptHandler` constructor of ExcepthandlerNode.
type ExceptHandler struct {
	Pos
	Type ExprNode   // expr? type
	Name string     // identifier? name
	Body []StmtNode // stmt* body
}

func (*ExceptHandler) isExcepthandlerNode() {}
func (n *ExceptHandler) GetPos() Pos        { return n.Pos }

// ExprNode is the ASDL sum type `expr` (one of 29 constructors).
type ExprNode interface {
	isExprNode()
	GetPos() Pos
}

// BoolOp is the `BoolOp` constructor of ExprNode.
type BoolOp struct {
	Pos
	Op     BoolopNode // boolop op
	Values []ExprNode // expr* values
}

func (*BoolOp) isExprNode()   {}
func (n *BoolOp) GetPos() Pos { return n.Pos }

// NamedExpr is the `NamedExpr` constructor of ExprNode.
type NamedExpr struct {
	Pos
	Target ExprNode // expr target
	Value  ExprNode // expr value
}

func (*NamedExpr) isExprNode()   {}
func (n *NamedExpr) GetPos() Pos { return n.Pos }

// BinOp is the `BinOp` constructor of ExprNode.
type BinOp struct {
	Pos
	Left  ExprNode     // expr left
	Op    OperatorNode // operator op
	Right ExprNode     // expr right
}

func (*BinOp) isExprNode()   {}
func (n *BinOp) GetPos() Pos { return n.Pos }

// UnaryOp is the `UnaryOp` constructor of ExprNode.
type UnaryOp struct {
	Pos
	Op      UnaryopNode // unaryop op
	Operand ExprNode    // expr operand
}

func (*UnaryOp) isExprNode()   {}
func (n *UnaryOp) GetPos() Pos { return n.Pos }

// Lambda is the `Lambda` constructor of ExprNode.
type Lambda struct {
	Pos
	Args *Arguments // arguments args
	Body ExprNode   // expr body
}

func (*Lambda) isExprNode()   {}
func (n *Lambda) GetPos() Pos { return n.Pos }

// IfExp is the `IfExp` constructor of ExprNode.
type IfExp struct {
	Pos
	Test   ExprNode // expr test
	Body   ExprNode // expr body
	Orelse ExprNode // expr orelse
}

func (*IfExp) isExprNode()   {}
func (n *IfExp) GetPos() Pos { return n.Pos }

// Dict is the `Dict` constructor of ExprNode.
type Dict struct {
	Pos
	Keys   []ExprNode // expr?* keys
	Values []ExprNode // expr* values
}

func (*Dict) isExprNode()   {}
func (n *Dict) GetPos() Pos { return n.Pos }

// Set is the `Set` constructor of ExprNode.
type Set struct {
	Pos
	Elts []ExprNode // expr* elts
}

func (*Set) isExprNode()   {}
func (n *Set) GetPos() Pos { return n.Pos }

// ListComp is the `ListComp` constructor of ExprNode.
type ListComp struct {
	Pos
	Elt        ExprNode         // expr elt
	Generators []*Comprehension // comprehension* generators
}

func (*ListComp) isExprNode()   {}
func (n *ListComp) GetPos() Pos { return n.Pos }

// SetComp is the `SetComp` constructor of ExprNode.
type SetComp struct {
	Pos
	Elt        ExprNode         // expr elt
	Generators []*Comprehension // comprehension* generators
}

func (*SetComp) isExprNode()   {}
func (n *SetComp) GetPos() Pos { return n.Pos }

// DictComp is the `DictComp` constructor of ExprNode.
type DictComp struct {
	Pos
	Key        ExprNode         // expr key
	Value      ExprNode         // expr value
	Generators []*Comprehension // comprehension* generators
}

func (*DictComp) isExprNode()   {}
func (n *DictComp) GetPos() Pos { return n.Pos }

// GeneratorExp is the `GeneratorExp` constructor of ExprNode.
type GeneratorExp struct {
	Pos
	Elt        ExprNode         // expr elt
	Generators []*Comprehension // comprehension* generators
}

func (*GeneratorExp) isExprNode()   {}
func (n *GeneratorExp) GetPos() Pos { return n.Pos }

// Await is the `Await` constructor of ExprNode.
type Await struct {
	Pos
	Value ExprNode // expr value
}

func (*Await) isExprNode()   {}
func (n *Await) GetPos() Pos { return n.Pos }

// Yield is the `Yield` constructor of ExprNode.
type Yield struct {
	Pos
	Value ExprNode // expr? value
}

func (*Yield) isExprNode()   {}
func (n *Yield) GetPos() Pos { return n.Pos }

// YieldFrom is the `YieldFrom` constructor of ExprNode.
type YieldFrom struct {
	Pos
	Value ExprNode // expr value
}

func (*YieldFrom) isExprNode()   {}
func (n *YieldFrom) GetPos() Pos { return n.Pos }

// Compare is the `Compare` constructor of ExprNode.
type Compare struct {
	Pos
	Left        ExprNode    // expr left
	Ops         []CmpopNode // cmpop* ops
	Comparators []ExprNode  // expr* comparators
}

func (*Compare) isExprNode()   {}
func (n *Compare) GetPos() Pos { return n.Pos }

// Call is the `Call` constructor of ExprNode.
type Call struct {
	Pos
	Func     ExprNode   // expr func
	Args     []ExprNode // expr* args
	Keywords []*Keyword // keyword* keywords
}

func (*Call) isExprNode()   {}
func (n *Call) GetPos() Pos { return n.Pos }

// FormattedValue is the `FormattedValue` constructor of ExprNode.
type FormattedValue struct {
	Pos
	Value      ExprNode // expr value
	Conversion int      // int conversion
	FormatSpec ExprNode // expr? format_spec
}

func (*FormattedValue) isExprNode()   {}
func (n *FormattedValue) GetPos() Pos { return n.Pos }

// Interpolation is the `Interpolation` constructor of ExprNode.
type Interpolation struct {
	Pos
	Value      ExprNode      // expr value
	Str        ConstantValue // constant str
	Conversion int           // int conversion
	FormatSpec ExprNode      // expr? format_spec
}

func (*Interpolation) isExprNode()   {}
func (n *Interpolation) GetPos() Pos { return n.Pos }

// JoinedStr is the `JoinedStr` constructor of ExprNode.
type JoinedStr struct {
	Pos
	Values []ExprNode // expr* values
}

func (*JoinedStr) isExprNode()   {}
func (n *JoinedStr) GetPos() Pos { return n.Pos }

// TemplateStr is the `TemplateStr` constructor of ExprNode.
type TemplateStr struct {
	Pos
	Values []ExprNode // expr* values
}

func (*TemplateStr) isExprNode()   {}
func (n *TemplateStr) GetPos() Pos { return n.Pos }

// Constant is the `Constant` constructor of ExprNode.
type Constant struct {
	Pos
	Value ConstantValue // constant value
	Kind  string        // string? kind
}

func (*Constant) isExprNode()   {}
func (n *Constant) GetPos() Pos { return n.Pos }

// Attribute is the `Attribute` constructor of ExprNode.
type Attribute struct {
	Pos
	Value ExprNode        // expr value
	Attr  string          // identifier attr
	Ctx   ExprContextNode // expr_context ctx
}

func (*Attribute) isExprNode()   {}
func (n *Attribute) GetPos() Pos { return n.Pos }

// Subscript is the `Subscript` constructor of ExprNode.
type Subscript struct {
	Pos
	Value ExprNode        // expr value
	Slice ExprNode        // expr slice
	Ctx   ExprContextNode // expr_context ctx
}

func (*Subscript) isExprNode()   {}
func (n *Subscript) GetPos() Pos { return n.Pos }

// Starred is the `Starred` constructor of ExprNode.
type Starred struct {
	Pos
	Value ExprNode        // expr value
	Ctx   ExprContextNode // expr_context ctx
}

func (*Starred) isExprNode()   {}
func (n *Starred) GetPos() Pos { return n.Pos }

// Name is the `Name` constructor of ExprNode.
type Name struct {
	Pos
	Id  string          // identifier id
	Ctx ExprContextNode // expr_context ctx
}

func (*Name) isExprNode()   {}
func (n *Name) GetPos() Pos { return n.Pos }

// List is the `List` constructor of ExprNode.
type List struct {
	Pos
	Elts []ExprNode      // expr* elts
	Ctx  ExprContextNode // expr_context ctx
}

func (*List) isExprNode()   {}
func (n *List) GetPos() Pos { return n.Pos }

// Tuple is the `Tuple` constructor of ExprNode.
type Tuple struct {
	Pos
	Elts []ExprNode      // expr* elts
	Ctx  ExprContextNode // expr_context ctx
}

func (*Tuple) isExprNode()   {}
func (n *Tuple) GetPos() Pos { return n.Pos }

// Slice is the `Slice` constructor of ExprNode.
type Slice struct {
	Pos
	Lower ExprNode // expr? lower
	Upper ExprNode // expr? upper
	Step  ExprNode // expr? step
}

func (*Slice) isExprNode()   {}
func (n *Slice) GetPos() Pos { return n.Pos }

// ExprContextNode is the ASDL sum type `expr_context` (one of 3 constructors).
type ExprContextNode interface {
	isExprContextNode()
}

// Load is the `Load` constructor of ExprContextNode.
type Load struct {
}

func (*Load) isExprContextNode() {}

// Store is the `Store` constructor of ExprContextNode.
type Store struct {
}

func (*Store) isExprContextNode() {}

// Del is the `Del` constructor of ExprContextNode.
type Del struct {
}

func (*Del) isExprContextNode() {}

// Keyword is the ASDL product type `keyword`.
type Keyword struct {
	Pos
	Arg   string   // identifier? arg
	Value ExprNode // expr value
}

func (n *Keyword) GetPos() Pos { return n.Pos }

// MatchCase is the ASDL product type `match_case`.
type MatchCase struct {
	Pattern PatternNode // pattern pattern
	Guard   ExprNode    // expr? guard
	Body    []StmtNode  // stmt* body
}

// ModNode is the ASDL sum type `mod` (one of 4 constructors).
type ModNode interface {
	isModNode()
}

// Module is the `Module` constructor of ModNode.
type Module struct {
	Body        []StmtNode       // stmt* body
	TypeIgnores []TypeIgnoreNode // type_ignore* type_ignores
}

func (*Module) isModNode() {}

// Interactive is the `Interactive` constructor of ModNode.
type Interactive struct {
	Body []StmtNode // stmt* body
}

func (*Interactive) isModNode() {}

// Expression is the `Expression` constructor of ModNode.
type Expression struct {
	Body ExprNode // expr body
}

func (*Expression) isModNode() {}

// FunctionType is the `FunctionType` constructor of ModNode.
type FunctionType struct {
	Argtypes []ExprNode // expr* argtypes
	Returns  ExprNode   // expr returns
}

func (*FunctionType) isModNode() {}

// OperatorNode is the ASDL sum type `operator` (one of 13 constructors).
type OperatorNode interface {
	isOperatorNode()
}

// Add is the `Add` constructor of OperatorNode.
type Add struct {
}

func (*Add) isOperatorNode() {}

// Sub is the `Sub` constructor of OperatorNode.
type Sub struct {
}

func (*Sub) isOperatorNode() {}

// Mult is the `Mult` constructor of OperatorNode.
type Mult struct {
}

func (*Mult) isOperatorNode() {}

// MatMult is the `MatMult` constructor of OperatorNode.
type MatMult struct {
}

func (*MatMult) isOperatorNode() {}

// Div is the `Div` constructor of OperatorNode.
type Div struct {
}

func (*Div) isOperatorNode() {}

// Mod is the `Mod` constructor of OperatorNode.
type Mod struct {
}

func (*Mod) isOperatorNode() {}

// Pow is the `Pow` constructor of OperatorNode.
type Pow struct {
}

func (*Pow) isOperatorNode() {}

// LShift is the `LShift` constructor of OperatorNode.
type LShift struct {
}

func (*LShift) isOperatorNode() {}

// RShift is the `RShift` constructor of OperatorNode.
type RShift struct {
}

func (*RShift) isOperatorNode() {}

// BitOr is the `BitOr` constructor of OperatorNode.
type BitOr struct {
}

func (*BitOr) isOperatorNode() {}

// BitXor is the `BitXor` constructor of OperatorNode.
type BitXor struct {
}

func (*BitXor) isOperatorNode() {}

// BitAnd is the `BitAnd` constructor of OperatorNode.
type BitAnd struct {
}

func (*BitAnd) isOperatorNode() {}

// FloorDiv is the `FloorDiv` constructor of OperatorNode.
type FloorDiv struct {
}

func (*FloorDiv) isOperatorNode() {}

// PatternNode is the ASDL sum type `pattern` (one of 8 constructors).
type PatternNode interface {
	isPatternNode()
	GetPos() Pos
}

// MatchValue is the `MatchValue` constructor of PatternNode.
type MatchValue struct {
	Pos
	Value ExprNode // expr value
}

func (*MatchValue) isPatternNode() {}
func (n *MatchValue) GetPos() Pos  { return n.Pos }

// MatchSingleton is the `MatchSingleton` constructor of PatternNode.
type MatchSingleton struct {
	Pos
	Value ConstantValue // constant value
}

func (*MatchSingleton) isPatternNode() {}
func (n *MatchSingleton) GetPos() Pos  { return n.Pos }

// MatchSequence is the `MatchSequence` constructor of PatternNode.
type MatchSequence struct {
	Pos
	Patterns []PatternNode // pattern* patterns
}

func (*MatchSequence) isPatternNode() {}
func (n *MatchSequence) GetPos() Pos  { return n.Pos }

// MatchMapping is the `MatchMapping` constructor of PatternNode.
type MatchMapping struct {
	Pos
	Keys     []ExprNode    // expr* keys
	Patterns []PatternNode // pattern* patterns
	Rest     string        // identifier? rest
}

func (*MatchMapping) isPatternNode() {}
func (n *MatchMapping) GetPos() Pos  { return n.Pos }

// MatchClass is the `MatchClass` constructor of PatternNode.
type MatchClass struct {
	Pos
	Cls         ExprNode      // expr cls
	Patterns    []PatternNode // pattern* patterns
	KwdAttrs    []string      // identifier* kwd_attrs
	KwdPatterns []PatternNode // pattern* kwd_patterns
}

func (*MatchClass) isPatternNode() {}
func (n *MatchClass) GetPos() Pos  { return n.Pos }

// MatchStar is the `MatchStar` constructor of PatternNode.
type MatchStar struct {
	Pos
	Name string // identifier? name
}

func (*MatchStar) isPatternNode() {}
func (n *MatchStar) GetPos() Pos  { return n.Pos }

// MatchAs is the `MatchAs` constructor of PatternNode.
type MatchAs struct {
	Pos
	Pattern PatternNode // pattern? pattern
	Name    string      // identifier? name
}

func (*MatchAs) isPatternNode() {}
func (n *MatchAs) GetPos() Pos  { return n.Pos }

// MatchOr is the `MatchOr` constructor of PatternNode.
type MatchOr struct {
	Pos
	Patterns []PatternNode // pattern* patterns
}

func (*MatchOr) isPatternNode() {}
func (n *MatchOr) GetPos() Pos  { return n.Pos }

// StmtNode is the ASDL sum type `stmt` (one of 28 constructors).
type StmtNode interface {
	isStmtNode()
	GetPos() Pos
}

// FunctionDef is the `FunctionDef` constructor of StmtNode.
type FunctionDef struct {
	Pos
	Name          string          // identifier name
	Args          *Arguments      // arguments args
	Body          []StmtNode      // stmt* body
	DecoratorList []ExprNode      // expr* decorator_list
	Returns       ExprNode        // expr? returns
	TypeComment   string          // string? type_comment
	TypeParams    []TypeParamNode // type_param* type_params
}

func (*FunctionDef) isStmtNode()   {}
func (n *FunctionDef) GetPos() Pos { return n.Pos }

// AsyncFunctionDef is the `AsyncFunctionDef` constructor of StmtNode.
type AsyncFunctionDef struct {
	Pos
	Name          string          // identifier name
	Args          *Arguments      // arguments args
	Body          []StmtNode      // stmt* body
	DecoratorList []ExprNode      // expr* decorator_list
	Returns       ExprNode        // expr? returns
	TypeComment   string          // string? type_comment
	TypeParams    []TypeParamNode // type_param* type_params
}

func (*AsyncFunctionDef) isStmtNode()   {}
func (n *AsyncFunctionDef) GetPos() Pos { return n.Pos }

// ClassDef is the `ClassDef` constructor of StmtNode.
type ClassDef struct {
	Pos
	Name          string          // identifier name
	Bases         []ExprNode      // expr* bases
	Keywords      []*Keyword      // keyword* keywords
	Body          []StmtNode      // stmt* body
	DecoratorList []ExprNode      // expr* decorator_list
	TypeParams    []TypeParamNode // type_param* type_params
}

func (*ClassDef) isStmtNode()   {}
func (n *ClassDef) GetPos() Pos { return n.Pos }

// Return is the `Return` constructor of StmtNode.
type Return struct {
	Pos
	Value ExprNode // expr? value
}

func (*Return) isStmtNode()   {}
func (n *Return) GetPos() Pos { return n.Pos }

// Delete is the `Delete` constructor of StmtNode.
type Delete struct {
	Pos
	Targets []ExprNode // expr* targets
}

func (*Delete) isStmtNode()   {}
func (n *Delete) GetPos() Pos { return n.Pos }

// Assign is the `Assign` constructor of StmtNode.
type Assign struct {
	Pos
	Targets     []ExprNode // expr* targets
	Value       ExprNode   // expr value
	TypeComment string     // string? type_comment
}

func (*Assign) isStmtNode()   {}
func (n *Assign) GetPos() Pos { return n.Pos }

// TypeAlias is the `TypeAlias` constructor of StmtNode.
type TypeAlias struct {
	Pos
	Name       ExprNode        // expr name
	TypeParams []TypeParamNode // type_param* type_params
	Value      ExprNode        // expr value
}

func (*TypeAlias) isStmtNode()   {}
func (n *TypeAlias) GetPos() Pos { return n.Pos }

// AugAssign is the `AugAssign` constructor of StmtNode.
type AugAssign struct {
	Pos
	Target ExprNode     // expr target
	Op     OperatorNode // operator op
	Value  ExprNode     // expr value
}

func (*AugAssign) isStmtNode()   {}
func (n *AugAssign) GetPos() Pos { return n.Pos }

// AnnAssign is the `AnnAssign` constructor of StmtNode.
type AnnAssign struct {
	Pos
	Target     ExprNode // expr target
	Annotation ExprNode // expr annotation
	Value      ExprNode // expr? value
	Simple     int      // int simple
}

func (*AnnAssign) isStmtNode()   {}
func (n *AnnAssign) GetPos() Pos { return n.Pos }

// For is the `For` constructor of StmtNode.
type For struct {
	Pos
	Target      ExprNode   // expr target
	Iter        ExprNode   // expr iter
	Body        []StmtNode // stmt* body
	Orelse      []StmtNode // stmt* orelse
	TypeComment string     // string? type_comment
}

func (*For) isStmtNode()   {}
func (n *For) GetPos() Pos { return n.Pos }

// AsyncFor is the `AsyncFor` constructor of StmtNode.
type AsyncFor struct {
	Pos
	Target      ExprNode   // expr target
	Iter        ExprNode   // expr iter
	Body        []StmtNode // stmt* body
	Orelse      []StmtNode // stmt* orelse
	TypeComment string     // string? type_comment
}

func (*AsyncFor) isStmtNode()   {}
func (n *AsyncFor) GetPos() Pos { return n.Pos }

// While is the `While` constructor of StmtNode.
type While struct {
	Pos
	Test   ExprNode   // expr test
	Body   []StmtNode // stmt* body
	Orelse []StmtNode // stmt* orelse
}

func (*While) isStmtNode()   {}
func (n *While) GetPos() Pos { return n.Pos }

// If is the `If` constructor of StmtNode.
type If struct {
	Pos
	Test   ExprNode   // expr test
	Body   []StmtNode // stmt* body
	Orelse []StmtNode // stmt* orelse
}

func (*If) isStmtNode()   {}
func (n *If) GetPos() Pos { return n.Pos }

// With is the `With` constructor of StmtNode.
type With struct {
	Pos
	Items       []*Withitem // withitem* items
	Body        []StmtNode  // stmt* body
	TypeComment string      // string? type_comment
}

func (*With) isStmtNode()   {}
func (n *With) GetPos() Pos { return n.Pos }

// AsyncWith is the `AsyncWith` constructor of StmtNode.
type AsyncWith struct {
	Pos
	Items       []*Withitem // withitem* items
	Body        []StmtNode  // stmt* body
	TypeComment string      // string? type_comment
}

func (*AsyncWith) isStmtNode()   {}
func (n *AsyncWith) GetPos() Pos { return n.Pos }

// Match is the `Match` constructor of StmtNode.
type Match struct {
	Pos
	Subject ExprNode     // expr subject
	Cases   []*MatchCase // match_case* cases
}

func (*Match) isStmtNode()   {}
func (n *Match) GetPos() Pos { return n.Pos }

// Raise is the `Raise` constructor of StmtNode.
type Raise struct {
	Pos
	Exc   ExprNode // expr? exc
	Cause ExprNode // expr? cause
}

func (*Raise) isStmtNode()   {}
func (n *Raise) GetPos() Pos { return n.Pos }

// Try is the `Try` constructor of StmtNode.
type Try struct {
	Pos
	Body      []StmtNode          // stmt* body
	Handlers  []ExcepthandlerNode // excepthandler* handlers
	Orelse    []StmtNode          // stmt* orelse
	Finalbody []StmtNode          // stmt* finalbody
}

func (*Try) isStmtNode()   {}
func (n *Try) GetPos() Pos { return n.Pos }

// TryStar is the `TryStar` constructor of StmtNode.
type TryStar struct {
	Pos
	Body      []StmtNode          // stmt* body
	Handlers  []ExcepthandlerNode // excepthandler* handlers
	Orelse    []StmtNode          // stmt* orelse
	Finalbody []StmtNode          // stmt* finalbody
}

func (*TryStar) isStmtNode()   {}
func (n *TryStar) GetPos() Pos { return n.Pos }

// Assert is the `Assert` constructor of StmtNode.
type Assert struct {
	Pos
	Test ExprNode // expr test
	Msg  ExprNode // expr? msg
}

func (*Assert) isStmtNode()   {}
func (n *Assert) GetPos() Pos { return n.Pos }

// Import is the `Import` constructor of StmtNode.
type Import struct {
	Pos
	Names []*Alias // alias* names
}

func (*Import) isStmtNode()   {}
func (n *Import) GetPos() Pos { return n.Pos }

// ImportFrom is the `ImportFrom` constructor of StmtNode.
type ImportFrom struct {
	Pos
	Module string   // identifier? module
	Names  []*Alias // alias* names
	Level  int      // int? level
}

func (*ImportFrom) isStmtNode()   {}
func (n *ImportFrom) GetPos() Pos { return n.Pos }

// Global is the `Global` constructor of StmtNode.
type Global struct {
	Pos
	Names []string // identifier* names
}

func (*Global) isStmtNode()   {}
func (n *Global) GetPos() Pos { return n.Pos }

// Nonlocal is the `Nonlocal` constructor of StmtNode.
type Nonlocal struct {
	Pos
	Names []string // identifier* names
}

func (*Nonlocal) isStmtNode()   {}
func (n *Nonlocal) GetPos() Pos { return n.Pos }

// Expr is the `Expr` constructor of StmtNode.
type Expr struct {
	Pos
	Value ExprNode // expr value
}

func (*Expr) isStmtNode()   {}
func (n *Expr) GetPos() Pos { return n.Pos }

// Pass is the `Pass` constructor of StmtNode.
type Pass struct {
	Pos
}

func (*Pass) isStmtNode()   {}
func (n *Pass) GetPos() Pos { return n.Pos }

// Break is the `Break` constructor of StmtNode.
type Break struct {
	Pos
}

func (*Break) isStmtNode()   {}
func (n *Break) GetPos() Pos { return n.Pos }

// Continue is the `Continue` constructor of StmtNode.
type Continue struct {
	Pos
}

func (*Continue) isStmtNode()   {}
func (n *Continue) GetPos() Pos { return n.Pos }

// TypeIgnoreNode is the ASDL sum type `type_ignore` (one of 1 constructors).
type TypeIgnoreNode interface {
	isTypeIgnoreNode()
}

// TypeIgnore is the `TypeIgnore` constructor of TypeIgnoreNode.
type TypeIgnore struct {
	Lineno int    // int lineno
	Tag    string // string tag
}

func (*TypeIgnore) isTypeIgnoreNode() {}

// TypeParamNode is the ASDL sum type `type_param` (one of 3 constructors).
type TypeParamNode interface {
	isTypeParamNode()
	GetPos() Pos
}

// TypeVar is the `TypeVar` constructor of TypeParamNode.
type TypeVar struct {
	Pos
	Name         string   // identifier name
	Bound        ExprNode // expr? bound
	DefaultValue ExprNode // expr? default_value
}

func (*TypeVar) isTypeParamNode() {}
func (n *TypeVar) GetPos() Pos    { return n.Pos }

// ParamSpec is the `ParamSpec` constructor of TypeParamNode.
type ParamSpec struct {
	Pos
	Name         string   // identifier name
	DefaultValue ExprNode // expr? default_value
}

func (*ParamSpec) isTypeParamNode() {}
func (n *ParamSpec) GetPos() Pos    { return n.Pos }

// TypeVarTuple is the `TypeVarTuple` constructor of TypeParamNode.
type TypeVarTuple struct {
	Pos
	Name         string   // identifier name
	DefaultValue ExprNode // expr? default_value
}

func (*TypeVarTuple) isTypeParamNode() {}
func (n *TypeVarTuple) GetPos() Pos    { return n.Pos }

// UnaryopNode is the ASDL sum type `unaryop` (one of 4 constructors).
type UnaryopNode interface {
	isUnaryopNode()
}

// Invert is the `Invert` constructor of UnaryopNode.
type Invert struct {
}

func (*Invert) isUnaryopNode() {}

// Not is the `Not` constructor of UnaryopNode.
type Not struct {
}

func (*Not) isUnaryopNode() {}

// UAdd is the `UAdd` constructor of UnaryopNode.
type UAdd struct {
}

func (*UAdd) isUnaryopNode() {}

// USub is the `USub` constructor of UnaryopNode.
type USub struct {
}

func (*USub) isUnaryopNode() {}

// Withitem is the ASDL product type `withitem`.
type Withitem struct {
	ContextExpr  ExprNode // expr context_expr
	OptionalVars ExprNode // expr? optional_vars
}
