// Code generated by internal/asdlgen. DO NOT EDIT.
// Source: internal/asdlgen/Python.asdl

package ast

// transformChildren reads each node-typed child slot, runs Apply on it, and
// writes the (possibly replaced) value back. Generated mirror of
// walkChildren — see transform.go for the surrounding driver and semantics.
func transformChildren(n Node, t Transformer) {
	switch n := n.(type) {
	case *Arg:
		n.Annotation = transformOne[ExprNode](t, n.Annotation)
	case *Arguments:
		n.Posonlyargs = transformList[*Arg](t, n.Posonlyargs)
		n.Args = transformList[*Arg](t, n.Args)
		n.Vararg = transformOne[*Arg](t, n.Vararg)
		n.Kwonlyargs = transformList[*Arg](t, n.Kwonlyargs)
		n.KwDefaults = transformList[ExprNode](t, n.KwDefaults)
		n.Kwarg = transformOne[*Arg](t, n.Kwarg)
		n.Defaults = transformList[ExprNode](t, n.Defaults)
	case *Comprehension:
		n.Target = transformOne[ExprNode](t, n.Target)
		n.Iter = transformOne[ExprNode](t, n.Iter)
		n.Ifs = transformList[ExprNode](t, n.Ifs)
	case *ExceptHandler:
		n.Type = transformOne[ExprNode](t, n.Type)
		n.Body = transformList[StmtNode](t, n.Body)
	case *BoolOp:
		n.Op = transformOne[BoolopNode](t, n.Op)
		n.Values = transformList[ExprNode](t, n.Values)
	case *NamedExpr:
		n.Target = transformOne[ExprNode](t, n.Target)
		n.Value = transformOne[ExprNode](t, n.Value)
	case *BinOp:
		n.Left = transformOne[ExprNode](t, n.Left)
		n.Op = transformOne[OperatorNode](t, n.Op)
		n.Right = transformOne[ExprNode](t, n.Right)
	case *UnaryOp:
		n.Op = transformOne[UnaryopNode](t, n.Op)
		n.Operand = transformOne[ExprNode](t, n.Operand)
	case *Lambda:
		n.Args = transformOne[*Arguments](t, n.Args)
		n.Body = transformOne[ExprNode](t, n.Body)
	case *IfExp:
		n.Test = transformOne[ExprNode](t, n.Test)
		n.Body = transformOne[ExprNode](t, n.Body)
		n.Orelse = transformOne[ExprNode](t, n.Orelse)
	case *Dict:
		n.Keys = transformList[ExprNode](t, n.Keys)
		n.Values = transformList[ExprNode](t, n.Values)
	case *Set:
		n.Elts = transformList[ExprNode](t, n.Elts)
	case *ListComp:
		n.Elt = transformOne[ExprNode](t, n.Elt)
		n.Generators = transformList[*Comprehension](t, n.Generators)
	case *SetComp:
		n.Elt = transformOne[ExprNode](t, n.Elt)
		n.Generators = transformList[*Comprehension](t, n.Generators)
	case *DictComp:
		n.Key = transformOne[ExprNode](t, n.Key)
		n.Value = transformOne[ExprNode](t, n.Value)
		n.Generators = transformList[*Comprehension](t, n.Generators)
	case *GeneratorExp:
		n.Elt = transformOne[ExprNode](t, n.Elt)
		n.Generators = transformList[*Comprehension](t, n.Generators)
	case *Await:
		n.Value = transformOne[ExprNode](t, n.Value)
	case *Yield:
		n.Value = transformOne[ExprNode](t, n.Value)
	case *YieldFrom:
		n.Value = transformOne[ExprNode](t, n.Value)
	case *Compare:
		n.Left = transformOne[ExprNode](t, n.Left)
		n.Ops = transformList[CmpopNode](t, n.Ops)
		n.Comparators = transformList[ExprNode](t, n.Comparators)
	case *Call:
		n.Func = transformOne[ExprNode](t, n.Func)
		n.Args = transformList[ExprNode](t, n.Args)
		n.Keywords = transformList[*Keyword](t, n.Keywords)
	case *FormattedValue:
		n.Value = transformOne[ExprNode](t, n.Value)
		n.FormatSpec = transformOne[ExprNode](t, n.FormatSpec)
	case *Interpolation:
		n.Value = transformOne[ExprNode](t, n.Value)
		n.FormatSpec = transformOne[ExprNode](t, n.FormatSpec)
	case *JoinedStr:
		n.Values = transformList[ExprNode](t, n.Values)
	case *TemplateStr:
		n.Values = transformList[ExprNode](t, n.Values)
	case *Attribute:
		n.Value = transformOne[ExprNode](t, n.Value)
		n.Ctx = transformOne[ExprContextNode](t, n.Ctx)
	case *Subscript:
		n.Value = transformOne[ExprNode](t, n.Value)
		n.Slice = transformOne[ExprNode](t, n.Slice)
		n.Ctx = transformOne[ExprContextNode](t, n.Ctx)
	case *Starred:
		n.Value = transformOne[ExprNode](t, n.Value)
		n.Ctx = transformOne[ExprContextNode](t, n.Ctx)
	case *Name:
		n.Ctx = transformOne[ExprContextNode](t, n.Ctx)
	case *List:
		n.Elts = transformList[ExprNode](t, n.Elts)
		n.Ctx = transformOne[ExprContextNode](t, n.Ctx)
	case *Tuple:
		n.Elts = transformList[ExprNode](t, n.Elts)
		n.Ctx = transformOne[ExprContextNode](t, n.Ctx)
	case *Slice:
		n.Lower = transformOne[ExprNode](t, n.Lower)
		n.Upper = transformOne[ExprNode](t, n.Upper)
		n.Step = transformOne[ExprNode](t, n.Step)
	case *Keyword:
		n.Value = transformOne[ExprNode](t, n.Value)
	case *MatchCase:
		n.Pattern = transformOne[PatternNode](t, n.Pattern)
		n.Guard = transformOne[ExprNode](t, n.Guard)
		n.Body = transformList[StmtNode](t, n.Body)
	case *Module:
		n.Body = transformList[StmtNode](t, n.Body)
		n.TypeIgnores = transformList[TypeIgnoreNode](t, n.TypeIgnores)
	case *Interactive:
		n.Body = transformList[StmtNode](t, n.Body)
	case *Expression:
		n.Body = transformOne[ExprNode](t, n.Body)
	case *FunctionType:
		n.Argtypes = transformList[ExprNode](t, n.Argtypes)
		n.Returns = transformOne[ExprNode](t, n.Returns)
	case *MatchValue:
		n.Value = transformOne[ExprNode](t, n.Value)
	case *MatchSequence:
		n.Patterns = transformList[PatternNode](t, n.Patterns)
	case *MatchMapping:
		n.Keys = transformList[ExprNode](t, n.Keys)
		n.Patterns = transformList[PatternNode](t, n.Patterns)
	case *MatchClass:
		n.Cls = transformOne[ExprNode](t, n.Cls)
		n.Patterns = transformList[PatternNode](t, n.Patterns)
		n.KwdPatterns = transformList[PatternNode](t, n.KwdPatterns)
	case *MatchAs:
		n.Pattern = transformOne[PatternNode](t, n.Pattern)
	case *MatchOr:
		n.Patterns = transformList[PatternNode](t, n.Patterns)
	case *FunctionDef:
		n.Args = transformOne[*Arguments](t, n.Args)
		n.Body = transformList[StmtNode](t, n.Body)
		n.DecoratorList = transformList[ExprNode](t, n.DecoratorList)
		n.Returns = transformOne[ExprNode](t, n.Returns)
		n.TypeParams = transformList[TypeParamNode](t, n.TypeParams)
	case *AsyncFunctionDef:
		n.Args = transformOne[*Arguments](t, n.Args)
		n.Body = transformList[StmtNode](t, n.Body)
		n.DecoratorList = transformList[ExprNode](t, n.DecoratorList)
		n.Returns = transformOne[ExprNode](t, n.Returns)
		n.TypeParams = transformList[TypeParamNode](t, n.TypeParams)
	case *ClassDef:
		n.Bases = transformList[ExprNode](t, n.Bases)
		n.Keywords = transformList[*Keyword](t, n.Keywords)
		n.Body = transformList[StmtNode](t, n.Body)
		n.DecoratorList = transformList[ExprNode](t, n.DecoratorList)
		n.TypeParams = transformList[TypeParamNode](t, n.TypeParams)
	case *Return:
		n.Value = transformOne[ExprNode](t, n.Value)
	case *Delete:
		n.Targets = transformList[ExprNode](t, n.Targets)
	case *Assign:
		n.Targets = transformList[ExprNode](t, n.Targets)
		n.Value = transformOne[ExprNode](t, n.Value)
	case *TypeAlias:
		n.Name = transformOne[ExprNode](t, n.Name)
		n.TypeParams = transformList[TypeParamNode](t, n.TypeParams)
		n.Value = transformOne[ExprNode](t, n.Value)
	case *AugAssign:
		n.Target = transformOne[ExprNode](t, n.Target)
		n.Op = transformOne[OperatorNode](t, n.Op)
		n.Value = transformOne[ExprNode](t, n.Value)
	case *AnnAssign:
		n.Target = transformOne[ExprNode](t, n.Target)
		n.Annotation = transformOne[ExprNode](t, n.Annotation)
		n.Value = transformOne[ExprNode](t, n.Value)
	case *For:
		n.Target = transformOne[ExprNode](t, n.Target)
		n.Iter = transformOne[ExprNode](t, n.Iter)
		n.Body = transformList[StmtNode](t, n.Body)
		n.Orelse = transformList[StmtNode](t, n.Orelse)
	case *AsyncFor:
		n.Target = transformOne[ExprNode](t, n.Target)
		n.Iter = transformOne[ExprNode](t, n.Iter)
		n.Body = transformList[StmtNode](t, n.Body)
		n.Orelse = transformList[StmtNode](t, n.Orelse)
	case *While:
		n.Test = transformOne[ExprNode](t, n.Test)
		n.Body = transformList[StmtNode](t, n.Body)
		n.Orelse = transformList[StmtNode](t, n.Orelse)
	case *If:
		n.Test = transformOne[ExprNode](t, n.Test)
		n.Body = transformList[StmtNode](t, n.Body)
		n.Orelse = transformList[StmtNode](t, n.Orelse)
	case *With:
		n.Items = transformList[*Withitem](t, n.Items)
		n.Body = transformList[StmtNode](t, n.Body)
	case *AsyncWith:
		n.Items = transformList[*Withitem](t, n.Items)
		n.Body = transformList[StmtNode](t, n.Body)
	case *Match:
		n.Subject = transformOne[ExprNode](t, n.Subject)
		n.Cases = transformList[*MatchCase](t, n.Cases)
	case *Raise:
		n.Exc = transformOne[ExprNode](t, n.Exc)
		n.Cause = transformOne[ExprNode](t, n.Cause)
	case *Try:
		n.Body = transformList[StmtNode](t, n.Body)
		n.Handlers = transformList[ExcepthandlerNode](t, n.Handlers)
		n.Orelse = transformList[StmtNode](t, n.Orelse)
		n.Finalbody = transformList[StmtNode](t, n.Finalbody)
	case *TryStar:
		n.Body = transformList[StmtNode](t, n.Body)
		n.Handlers = transformList[ExcepthandlerNode](t, n.Handlers)
		n.Orelse = transformList[StmtNode](t, n.Orelse)
		n.Finalbody = transformList[StmtNode](t, n.Finalbody)
	case *Assert:
		n.Test = transformOne[ExprNode](t, n.Test)
		n.Msg = transformOne[ExprNode](t, n.Msg)
	case *Import:
		n.Names = transformList[*Alias](t, n.Names)
	case *ImportFrom:
		n.Names = transformList[*Alias](t, n.Names)
	case *Expr:
		n.Value = transformOne[ExprNode](t, n.Value)
	case *TypeVar:
		n.Bound = transformOne[ExprNode](t, n.Bound)
		n.DefaultValue = transformOne[ExprNode](t, n.DefaultValue)
	case *ParamSpec:
		n.DefaultValue = transformOne[ExprNode](t, n.DefaultValue)
	case *TypeVarTuple:
		n.DefaultValue = transformOne[ExprNode](t, n.DefaultValue)
	case *Withitem:
		n.ContextExpr = transformOne[ExprNode](t, n.ContextExpr)
		n.OptionalVars = transformOne[ExprNode](t, n.OptionalVars)
	}
}
