// Code generated by internal/asdlgen. DO NOT EDIT.
// Source: internal/asdlgen/Python.asdl

package ast

// Node is the union of every AST node type produced by the generator.
// Concrete sum-type interfaces (Stmt, Expr, ...) all satisfy Node.
type Node interface{}

// Walk traverses an AST in depth-first order. For each non-nil node, it calls
// fn(n); if fn returns false, the children of n are skipped.
func Walk(n Node, fn func(Node) bool) {
	if n == nil {
		return
	}
	if !fn(n) {
		return
	}
	walkChildren(n, fn)
}

func walkChildren(n Node, fn func(Node) bool) {
	switch n := n.(type) {
	case *Arg:
		Walk(n.Annotation, fn)
	case *Arguments:
		for _, c := range n.Posonlyargs {
			Walk(c, fn)
		}
		for _, c := range n.Args {
			Walk(c, fn)
		}
		Walk(n.Vararg, fn)
		for _, c := range n.Kwonlyargs {
			Walk(c, fn)
		}
		for _, c := range n.KwDefaults {
			Walk(c, fn)
		}
		Walk(n.Kwarg, fn)
		for _, c := range n.Defaults {
			Walk(c, fn)
		}
	case *Comprehension:
		Walk(n.Target, fn)
		Walk(n.Iter, fn)
		for _, c := range n.Ifs {
			Walk(c, fn)
		}
	case *ExceptHandler:
		Walk(n.Type, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
	case *BoolOp:
		Walk(n.Op, fn)
		for _, c := range n.Values {
			Walk(c, fn)
		}
	case *NamedExpr:
		Walk(n.Target, fn)
		Walk(n.Value, fn)
	case *BinOp:
		Walk(n.Left, fn)
		Walk(n.Op, fn)
		Walk(n.Right, fn)
	case *UnaryOp:
		Walk(n.Op, fn)
		Walk(n.Operand, fn)
	case *Lambda:
		Walk(n.Args, fn)
		Walk(n.Body, fn)
	case *IfExp:
		Walk(n.Test, fn)
		Walk(n.Body, fn)
		Walk(n.Orelse, fn)
	case *Dict:
		for _, c := range n.Keys {
			Walk(c, fn)
		}
		for _, c := range n.Values {
			Walk(c, fn)
		}
	case *Set:
		for _, c := range n.Elts {
			Walk(c, fn)
		}
	case *ListComp:
		Walk(n.Elt, fn)
		for _, c := range n.Generators {
			Walk(c, fn)
		}
	case *SetComp:
		Walk(n.Elt, fn)
		for _, c := range n.Generators {
			Walk(c, fn)
		}
	case *DictComp:
		Walk(n.Key, fn)
		Walk(n.Value, fn)
		for _, c := range n.Generators {
			Walk(c, fn)
		}
	case *GeneratorExp:
		Walk(n.Elt, fn)
		for _, c := range n.Generators {
			Walk(c, fn)
		}
	case *Await:
		Walk(n.Value, fn)
	case *Yield:
		Walk(n.Value, fn)
	case *YieldFrom:
		Walk(n.Value, fn)
	case *Compare:
		Walk(n.Left, fn)
		for _, c := range n.Ops {
			Walk(c, fn)
		}
		for _, c := range n.Comparators {
			Walk(c, fn)
		}
	case *Call:
		Walk(n.Func, fn)
		for _, c := range n.Args {
			Walk(c, fn)
		}
		for _, c := range n.Keywords {
			Walk(c, fn)
		}
	case *FormattedValue:
		Walk(n.Value, fn)
		Walk(n.FormatSpec, fn)
	case *Interpolation:
		Walk(n.Value, fn)
		Walk(n.FormatSpec, fn)
	case *JoinedStr:
		for _, c := range n.Values {
			Walk(c, fn)
		}
	case *TemplateStr:
		for _, c := range n.Values {
			Walk(c, fn)
		}
	case *Attribute:
		Walk(n.Value, fn)
		Walk(n.Ctx, fn)
	case *Subscript:
		Walk(n.Value, fn)
		Walk(n.Slice, fn)
		Walk(n.Ctx, fn)
	case *Starred:
		Walk(n.Value, fn)
		Walk(n.Ctx, fn)
	case *Name:
		Walk(n.Ctx, fn)
	case *List:
		for _, c := range n.Elts {
			Walk(c, fn)
		}
		Walk(n.Ctx, fn)
	case *Tuple:
		for _, c := range n.Elts {
			Walk(c, fn)
		}
		Walk(n.Ctx, fn)
	case *Slice:
		Walk(n.Lower, fn)
		Walk(n.Upper, fn)
		Walk(n.Step, fn)
	case *Keyword:
		Walk(n.Value, fn)
	case *MatchCase:
		Walk(n.Pattern, fn)
		Walk(n.Guard, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
	case *Module:
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.TypeIgnores {
			Walk(c, fn)
		}
	case *Interactive:
		for _, c := range n.Body {
			Walk(c, fn)
		}
	case *Expression:
		Walk(n.Body, fn)
	case *FunctionType:
		for _, c := range n.Argtypes {
			Walk(c, fn)
		}
		Walk(n.Returns, fn)
	case *MatchValue:
		Walk(n.Value, fn)
	case *MatchSequence:
		for _, c := range n.Patterns {
			Walk(c, fn)
		}
	case *MatchMapping:
		for _, c := range n.Keys {
			Walk(c, fn)
		}
		for _, c := range n.Patterns {
			Walk(c, fn)
		}
	case *MatchClass:
		Walk(n.Cls, fn)
		for _, c := range n.Patterns {
			Walk(c, fn)
		}
		for _, c := range n.KwdPatterns {
			Walk(c, fn)
		}
	case *MatchAs:
		Walk(n.Pattern, fn)
	case *MatchOr:
		for _, c := range n.Patterns {
			Walk(c, fn)
		}
	case *FunctionDef:
		Walk(n.Args, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.DecoratorList {
			Walk(c, fn)
		}
		Walk(n.Returns, fn)
		for _, c := range n.TypeParams {
			Walk(c, fn)
		}
	case *AsyncFunctionDef:
		Walk(n.Args, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.DecoratorList {
			Walk(c, fn)
		}
		Walk(n.Returns, fn)
		for _, c := range n.TypeParams {
			Walk(c, fn)
		}
	case *ClassDef:
		for _, c := range n.Bases {
			Walk(c, fn)
		}
		for _, c := range n.Keywords {
			Walk(c, fn)
		}
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.DecoratorList {
			Walk(c, fn)
		}
		for _, c := range n.TypeParams {
			Walk(c, fn)
		}
	case *Return:
		Walk(n.Value, fn)
	case *Delete:
		for _, c := range n.Targets {
			Walk(c, fn)
		}
	case *Assign:
		for _, c := range n.Targets {
			Walk(c, fn)
		}
		Walk(n.Value, fn)
	case *TypeAlias:
		Walk(n.Name, fn)
		for _, c := range n.TypeParams {
			Walk(c, fn)
		}
		Walk(n.Value, fn)
	case *AugAssign:
		Walk(n.Target, fn)
		Walk(n.Op, fn)
		Walk(n.Value, fn)
	case *AnnAssign:
		Walk(n.Target, fn)
		Walk(n.Annotation, fn)
		Walk(n.Value, fn)
	case *For:
		Walk(n.Target, fn)
		Walk(n.Iter, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.Orelse {
			Walk(c, fn)
		}
	case *AsyncFor:
		Walk(n.Target, fn)
		Walk(n.Iter, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.Orelse {
			Walk(c, fn)
		}
	case *While:
		Walk(n.Test, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.Orelse {
			Walk(c, fn)
		}
	case *If:
		Walk(n.Test, fn)
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.Orelse {
			Walk(c, fn)
		}
	case *With:
		for _, c := range n.Items {
			Walk(c, fn)
		}
		for _, c := range n.Body {
			Walk(c, fn)
		}
	case *AsyncWith:
		for _, c := range n.Items {
			Walk(c, fn)
		}
		for _, c := range n.Body {
			Walk(c, fn)
		}
	case *Match:
		Walk(n.Subject, fn)
		for _, c := range n.Cases {
			Walk(c, fn)
		}
	case *Raise:
		Walk(n.Exc, fn)
		Walk(n.Cause, fn)
	case *Try:
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.Handlers {
			Walk(c, fn)
		}
		for _, c := range n.Orelse {
			Walk(c, fn)
		}
		for _, c := range n.Finalbody {
			Walk(c, fn)
		}
	case *TryStar:
		for _, c := range n.Body {
			Walk(c, fn)
		}
		for _, c := range n.Handlers {
			Walk(c, fn)
		}
		for _, c := range n.Orelse {
			Walk(c, fn)
		}
		for _, c := range n.Finalbody {
			Walk(c, fn)
		}
	case *Assert:
		Walk(n.Test, fn)
		Walk(n.Msg, fn)
	case *Import:
		for _, c := range n.Names {
			Walk(c, fn)
		}
	case *ImportFrom:
		for _, c := range n.Names {
			Walk(c, fn)
		}
	case *Expr:
		Walk(n.Value, fn)
	case *TypeVar:
		Walk(n.Bound, fn)
		Walk(n.DefaultValue, fn)
	case *ParamSpec:
		Walk(n.DefaultValue, fn)
	case *TypeVarTuple:
		Walk(n.DefaultValue, fn)
	case *Withitem:
		Walk(n.ContextExpr, fn)
		Walk(n.OptionalVars, fn)
	}
}
